"""empty message

Revision ID: 98441ead6e4a
Revises: 
Create Date: 2024-06-08 17:14:18.032352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98441ead6e4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precipitation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('precip_mm', sa.Float(), nullable=False),
    sa.Column('precip_in', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.Column('sunrise', sa.Time(), nullable=False),
    sa.Column('wind_degree', sa.Integer(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Enum('N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW', 'WNW', 'NNW', 'SSE', 'WSW', 'ENE', 'ESE', 'NNE', 'SSW', name='winddirectionenum'), nullable=False),
    sa.Column('is_it_safe_to_go_out', sa.Boolean(), nullable=False),
    sa.Column('precipitation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['precipitation_id'], ['precipitation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    op.drop_table('precipitation')
    # ### end Alembic commands ###
